export const data = [
  {
    dkCodeAffaire: 'A00001334R',
    dkCodeSee: 'E00011941Z',
    dkCode: 'S00008548J',
    libelleAffaire: "GRENOBLE (38) - PORTES DE L'OUEST",
    libelleSee: "SEE GRENOBLE PORTES DE L'OUEST",
    libelle: "GRENOBLE PORTES DE L'OUEST",
    commentaireSite: "LES PORTES DE L'OUEST",
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00001334R',
        dkCodeSee: 'E00011941Z',
        dkCode: 'T00027714P',
        libelleAffaire: "GRENOBLE (38) - PORTES DE L'OUEST",
        libelleSee: "SEE GRENOBLE PORTES DE L'OUEST",
        libelle: "CHAUFFAGE PORTES DE L'OUEST",
        commentaireSite: "LES PORTES DE L'OUEST",
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00001336T',
    dkCodeSee: 'E00009475X',
    dkCode: 'S00012930N',
    libelleAffaire: 'GRENOBLE (38) - RES LES HAUTS DU PARC',
    libelleSee: 'SEE GRENOBLE RES LES HAUTS DU PARC',
    libelle: 'GRENOBLE RES LES HAUTS DU PARC',
    commentaireSite: 'LES HAUTS DU PARC',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00001336T',
        dkCodeSee: 'E00009475X',
        dkCode: 'T00026752X',
        libelleAffaire: 'GRENOBLE (38) - RES LES HAUTS DU PARC',
        libelleSee: 'SEE GRENOBLE RES LES HAUTS DU PARC',
        libelle: 'CHAUFFAGE 2 18 R PHELBRONNER',
        commentaireSite: 'LES HAUTS DU PARC',
        etatSite: 'En production',
      },
      {
        dkCodeAffaire: 'A00001336T',
        dkCodeSee: 'E00009475X',
        dkCode: 'T00026752Z',
        libelleAffaire: 'GRENOBLE (38) - RES LES HAUTS DU PARC',
        libelleSee: 'SEE GRENOBLE RES LES HAUTS DU PARC',
        libelle: 'CLIMATISATION 2 18 R PHELBRONNER',
        commentaireSite: 'LES HAUTS DU PARC',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00011930L',
    dkCode: 'S00016161K',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: 'SEE GRENOBLE BATA PLCHDULLIN',
    libelle: 'GRENOBLE MALHERBE A (0001-1)',
    commentaireSite: 'MALHERBE A',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00011930L',
        dkCode: 'T00027741W',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: 'SEE GRENOBLE BATA PLCHDULLIN',
        libelle: 'CHAUFFAGE MALHERBE A (0001-1)',
        commentaireSite: 'MALHERBE A',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00015623H',
    dkCode: 'S00003598J',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: 'SEE GRENOBLE BATBC PLCHDULLIN',
    libelle: 'GRENOBLE MALHERBE B-C (0001-2)',
    commentaireSite: 'MALHERBE B-C',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00015623H',
        dkCode: 'T00027742X',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: 'SEE GRENOBLE BATBC PLCHDULLIN',
        libelle: 'CHECS MALHERBE B-C (0001-2)',
        commentaireSite: 'MALHERBE B-C',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00017383H',
    dkCode: 'S00011976E',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: 'SEE SEYSSINS VALVERT',
    libelle: 'SEYSSINS VALVERT (0486)',
    commentaireSite: 'LE VALVERT (486) (TLC GRD-GRT)',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00017383H',
        dkCode: 'T00027746B',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: 'SEE SEYSSINS VALVERT',
        libelle: 'CHECS VALVERT (0486)',
        commentaireSite: 'LE VALVERT (486) (TLC GRD-GRT)',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00017481V',
    dkCode: 'S00006032A',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: 'SEE SEYSSINS  LES JARDINS DU COTEAU (0527)',
    libelle: 'SEYSSINS LES JARDINS DU COTEAU (0527)',
    commentaireSite: 'LE JARDIN DU COTEAU',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00017481V',
        dkCode: 'T00123409J',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: 'SEE SEYSSINS  LES JARDINS DU COTEAU (0527)',
        libelle: 'CHAUF BOIS LES JARDINS DU COTEAU (0527)',
        commentaireSite: 'LE JARDIN DU COTEAU',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00075681F',
    dkCode: 'S00002913F',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: 'SEE SEYSSINS PRE NOUVEL',
    libelle: 'SEYSSINS PRE NOUVEL (0488)',
    commentaireSite: 'LES HAUTS DE SEYSSINS (488) (TLC GRD-GRT)',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00075681F',
        dkCode: 'T00027748D',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: 'SEE SEYSSINS PRE NOUVEL',
        libelle: 'CH + ECS PRE NOUVEL (0488)',
        commentaireSite: 'LES HAUTS DE SEYSSINS (488) (TLC GRD-GRT)',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00095539X',
    dkCode: 'S00128799E',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: 'SEE VEUREY-VOROIZE LES ECHALIERES',
    libelle: 'LES ECHALIERES (472)',
    commentaireSite: 'CHAUFF LES ECHALIERES (472) (TLC GRD-GRT)',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00095539X',
        dkCode: 'T00376526N',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: 'SEE VEUREY-VOROIZE LES ECHALIERES',
        libelle: 'CHAUFF LES ECHALIERES (472)',
        commentaireSite: 'CHAUFF LES ECHALIERES (472) (TLC GRD-GRT)',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00095540Y',
    dkCode: 'S00128800F',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: 'SEE VEUREY-VOROIZE LES TILLEULS',
    libelle: 'LES TILLEULS (474)',
    commentaireSite: 'CHAUFF + ECS LES TILLEULS (474) (TLC GRD-GRT)',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00095540Y',
        dkCode: 'T00376527P',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: 'SEE VEUREY-VOROIZE LES TILLEULS',
        libelle: 'CHAUFF + ECS LES TILLEULS (474)',
        commentaireSite: 'CHAUFF + ECS LES TILLEULS (474) (TLC GRD-GRT)',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00095541Z',
    dkCode: 'S00128801G',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: 'SEE SAINT-EGREVE ROUTE DE GRENOBLE',
    libelle: 'ROUTE DE GRENOBLE (491)',
    commentaireSite: 'CHAUFF + ECS ROUTE DE GRENOBLE (491) (TLC GRD-GRT)',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00095541Z',
        dkCode: 'T00376528R',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: 'SEE SAINT-EGREVE ROUTE DE GRENOBLE',
        libelle: 'CHAUFF + ECS ROUTE DE GRENOBLE (491)',
        commentaireSite: 'CHAUFF + ECS ROUTE DE GRENOBLE (491) (TLC GRD-GRT)',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00095542A',
    dkCode: 'S00128802H',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: "SEE SAINT-ISMIER LE HAMEAU D'AVALON (502)",
    libelle: "LE HAMEAU D'AVALON (502)",
    commentaireSite: "CHAUFF + ECS LE HAMEAU D'AVALON (502) (TLC GRD-GRT)",
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00095542A',
        dkCode: 'T00376529S',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: "SEE SAINT-ISMIER LE HAMEAU D'AVALON (502)",
        libelle: "CHAUFF + ECS LE HAMEAU D'AVALON (502)",
        commentaireSite: "CHAUFF + ECS LE HAMEAU D'AVALON (502) (TLC GRD-GRT)",
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00095543B',
    dkCode: 'S00128803J',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: "SEE VOIRON L'ESSENTIEL",
    libelle: "L'ESSENTIEL (539)",
    commentaireSite: "CHAUFF + ECS L'ESSENTIEL (539) (TLC GRD-GRT)",
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00095543B',
        dkCode: 'T00376530T',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: "SEE VOIRON L'ESSENTIEL",
        libelle: "CHAUFF + ECS L'ESSENTIEL (539)",
        commentaireSite: "CHAUFF + ECS L'ESSENTIEL (539) (TLC GRD-GRT)",
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00095545D',
    dkCode: 'S00128804K',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: 'SEE LE PONT DE CLAIX MOZART',
    libelle: 'MOZART (554)',
    commentaireSite: 'SITE MOZART (554)',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00095545D',
        dkCode: 'T00376531V',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: 'SEE LE PONT DE CLAIX MOZART',
        libelle: 'CHAUFF + ECS MOZART (554)',
        commentaireSite: 'SITE MOZART (554)',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00003034Y',
    dkCodeSee: 'E00099700A',
    dkCode: 'S00134628D',
    libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
    libelleSee: 'SEE SEYSSINS LE DIAMANT DU COTEAU (573)',
    libelle: 'SEYSSINS LE DIAMANT DU COTEAU (573)',
    commentaireSite: 'LE DIAMANT DU COTEAU (573)',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00003034Y',
        dkCodeSee: 'E00099700A',
        dkCode: 'T00382451X',
        libelleAffaire: 'GRENOBLE (38) - GRENOBLE HABITAT',
        libelleSee: 'SEE SEYSSINS LE DIAMANT DU COTEAU (573)',
        libelle: 'CHAUFF + ECS LE DIAMANT DU COTEAU (573)',
        commentaireSite: 'LE DIAMANT DU COTEAU (573)',
        etatSite: 'En production',
      },
    ],
  },
  {
    dkCodeAffaire: 'A00005074R',
    dkCodeSee: 'E00007411B',
    dkCode: 'S00018601H',
    libelleAffaire: 'GRENOBLE (38) - LESDIGUIERES (206 A 222)',
    libelleSee: 'SEE GRENOBLE LESDIGUIERES 206/222',
    libelle: 'GRENOBLE LESDIGUIERES 206/222',
    commentaireSite: 'LESDIGUIERES (DM le 13/01/22 4 histos vides ?)',
    etatSite: 'En production',
    children: [
      {
        dkCodeAffaire: 'A00005074R',
        dkCodeSee: 'E00007411B',
        dkCode: 'T00028464S',
        libelleAffaire: 'GRENOBLE (38) - LESDIGUIERES (206 A 222)',
        libelleSee: 'SEE GRENOBLE LESDIGUIERES 206/222',
        libelle: 'CHAUFFAGE et ECS',
        commentaireSite: 'LESDIGUIERES (DM le 13/01/22 4 histos vides ?)',
        etatSite: 'En production',
      },
    ],
  },
];
